---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-fedora33}-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vv: true
verifier:
    name: ansible
